%define op_halt 0x00            ; alteração de estado para "halted"
%define op_load 0x01            ; carregamento de um valor imediato para um registrador
%define op_add 0x02             ; adição de dois registradores, armazenando o resultado em um terceiro registrador 
%define op_sub 0x03             ; subtração de dois registradores, armazenando o resultado em um terceiro registrador
%define op_print 0x04           ; impressão do valor de um registrador
